# Generated by Django 3.2 on 2021-04-07 22:54

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sumario',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
